_target_: src.modules.base_module.BaseModule

# To avoiding copying of loss and metric names, during hydra initialization
# there is custom resolver which replaces __loss__ to loss.__class__.__name__
# and __metric__ to main_metric.__class__.__name__,
# for example: ${replace:"__metric__/valid"}
# Use quotes for defining internal value in ${replace:"..."} to avoid
# grammar problems with hydra config parser.

defaults:
  - _self_
  - network: tdcnnpp.yaml

loss:
  _target_: "src.modules.losses.MixItLoss"
  loss_func:
    _target_: src.modules.losses.MultiSrcNegSDR
    sdr_type: snr
  generalized: True
  reduction: mean


metrics:
  main:
    _target_: src.modules.metrics.components.separation.ScaleInvariantSignalNoiseRatio
  valid_best:
    _target_: torchmetrics.MaxMetric
  additional:
    SNR:
      _target_: src.modules.metrics.components.separation.SignalNoiseRatio
    SI_SNRi:
      _target_: src.modules.metrics.components.separation.ScaleInvariantSignalNoiseRatioImprovement

output_activation: null

optimizer:
  _target_: torch.optim.RAdam
  lr: 3.0e-4
  weight_decay: 1.0e-5

scheduler:
  scheduler:
    _target_: src.modules.components.lr_scheduler.WarmupLinearDecayScheduler
    warmup_percent: 0.01 # percent ie. 0.08 = 8%
    total_steps: -1
  extras:
    interval: "step"
    frequency: 1

logging:
  on_step: True
  on_epoch: True
  sync_dist: True
  prog_bar: True
