_target_: src.datamodules.base_datamodule.BaseDataModule

defaults:
  - _self_
  - loaders: default.yaml
  - transforms: default.yaml


# TODO can be changed to a single dataset and split into train/valid/test
datasets:
  train:
    _target_: src.datamodules.datasets.RandomDataset

  valid:
    _target_: src.datamodules.datasets.RandomDataset

  test:
    _target_: src.datamodules.datasets.RandomDataset
