train:  # list of the order of below defined transformations, these will be applied in parallel to a singe instance
  [#normalize_peak,
   supervised_audio_mixing,
   mixture_of_mixtures]

valid:
  [#normalize_peak,
   #instance_zscore,
   #supervised_audio_mixing,
   mixture_of_mixtures]

test:
  [#normalize_peak,
   #instance_zscore,
   #supervised_audio_mixing,
   mixture_of_mixtures]

mixture_of_mixtures:
  _target_: src.datamodules.components.audio_mixing.MixtureOfMixtures
  p: 1
  #normalization: ${..normalize_peak}

supervised_audio_mixing:
  _target_: src.datamodules.components.audio_mixing.SupervisedAudioMixing
  p: 1
  audio_paths:
    - ${paths.data_dir}/dcase
  #normalization: ${..normalize_peak}

normalize_peak:
  _target_: src.datamodules.components.normalization.NormalizePeak
  target_peak: 0.2
